
import { Inter } from "next/font/google";
import "./globals.css";
import bootstrap from "bootstrap/dist/css/bootstrap.css";
import Header from "@/Header";
import Footer from "@/Footer";
import Manu from "@/Manu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="text-center">
      <Header/>
      <Manu/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
